import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorosoke App</title>
        <meta name="description" content="Generated by created by macbright" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Image src="/images/Rectangle.png" alt="Vercel Logo" width={300} height={300} />
        </h1>

        <Link href="/heroSection/login">
          <a className={styles.btn}> Lend your Voice</a>
        </Link>
      </main>
    </div>
  )
}
