import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/login.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorosoke App</title>
        <meta name="description" content="Generated by created by macbright" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
        <Image src="/images/Rectangle.png" alt="Vercel Logo" width={50} height={50} />
        <h1 className={styles.heading}>Log in</h1>
        <p className={styles.paragraph}>Welcome, please continue with twitter to acess the platform.</p>

        <Link href="https://twitter.com" passHref={true}>
          <a className={styles.btn}><i className="bi bi-twitter"></i> Continue with Twitter</a>
        </Link>
        </div>

        <Link href="/heroSection/main">
        <a className={styles.contentFooter}>Want to know more about this application?<span className={styles.span}>See more here.</span></a>
        </Link>
      </main>
    </div>
  )
}
